name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.2"
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/checkout@v4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Config Lisence
        run: composer config http-basic.packages.larabiz.com ${{ secrets.TEST_LICENSE_KEY }} ${{ secrets.TEST_LICENSE_SECRET }}
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-scripts --no-progress --prefer-dist
      - name: Require Version Dependencies
        run: composer require larabizcms/core
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Installation
        run: |
          php artisan larabiz:install --admin-name=Admin --admin-email=admin@larabiz.com --admin-pass=admin@larabiz.com
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test
  tests-premium:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.2"
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/checkout@v4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Config Lisence
        run: composer config http-basic.packages.larabiz.com ${{ secrets.TEST_LICENSE_KEY }} ${{ secrets.TEST_LICENSE_SECRET }}
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-scripts --no-progress --prefer-dist
      - name: Require Version Dependencies
        run: composer require larabizcms/core
      - name: Require premium package
        run: composer require larabizcms/premium
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Installation
        run: |
          php artisan larabiz:install --admin-name=Admin --admin-email=admin@larabiz.com --admin-pass=admin@larabiz.com
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
      - name: Run Statis Build
        run: npm install && npm run build
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test
